name: 'Setup Continuous Integration'
description: 'Cache Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: Cache Dependencies
      uses: actions/cache@v2
      id: cache-primes
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Install Dependencies
      run: pnpm install
      shell: bash
