name: Continuous Integration

on:
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: 18.16.1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Continuous Integration
        uses: ./.github/actions/ci-setup

      - name: Lint Application
        run: pnpm lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Continuous Integration
        uses: ./.github/actions/ci-setup

      - name: Build Application
        run: pnpm build
