name: Continuous Integration

on:
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: 18.16.1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Continuous Integration
        uses: ./.github/actions/ci-setup

      - name: Lint Application
        run: pnpm lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Continuous Integration
        uses: ./.github/actions/ci-setup

      - name: Build Application
        run: pnpm build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: pnpm build
          start: pnpm start
          wait-on: 'http://localhost:3000'
